name: Test build for dependabot

on:
  push:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run build for production
        run: |
          npm run build

